name: Close Stale Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          only-labels: 'needs more info'
          stale-issue-label: stale
          stale-issue-message: >
            This issue has not had recent activity and has been marked as stale.
            Reply to keep it open – otherwise I will close it in a week.
